### ISSUE TITLE
Why is segment-behavior '_move' not documented/private?

### ISSUE THREAD

**Issue by justinlevi** [wavesjs/waves-ui#31]
Apologies for all of my questions/issues lately. 

Just wondering why the _move segment-behavior function is not documented and treated as a "private" method (I'm assuming the convention of using an underscore is demarcating private in this case)

http://wavesjs.github.io/waves-ui/class/src/behaviors/segment-behavior.js~SegmentBehavior.html

The reason I ask is that I've been bouncing back and forth between the documentation and the code to try and get a mental model of everything I have available to me.

**Comment by b-ma** [comment]
Hi, no worries for the issues, it's just that I don't have much time these days but I should respond to everything soon hopefully.

For the private aspect of the `_move` method, its just that the public API of a behavior (which is actually not very public, as it is called by the layer) is the `edit` method. `_move` is just a way to keep the code clean, but at the end everything could live in a big switch / if-else inside the `edit`method.
